// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    Cesium: typeof import('./src/components/Cesium.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    LayerItem: typeof import('./src/components/LayerItem.vue')['default']
    LayerList: typeof import('./src/components/LayerList.vue')['default']
    LayerSetting: typeof import('./src/components/LayerSetting.vue')['default']
    SettingItem: typeof import('./src/components/SettingItem.vue')['default']
  }
}

export { }
